sftp:
    # https://github.com/atmoz/sftp
    image: atmoz/sftp
    volumes:
        - ./config/users.conf:/etc/sftp/users.conf:ro
        - ./volume:/home
        - ./config/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub
        - ./config/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub
        - ./config/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
        - ./config/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
        - "2222:22"

